target-version = "py310"

exclude = [
    "**/test/**",
    # "*.ipynb",
]


[lint]
select = ["ALL"]
ignore = [
    # -- Must have --
    "D100",
    "D401", # First line should be in imperative mood
    "D105", # Function doc for every function
    "S101",
    "INP001", # __init__ for implicit namespace
    "T201", # No print,
    "E501", # Line too long
    "EXE002", # Use explicit exception handling
    
    # About TODO
    "TD002",
    "TD003",
    "FIX002",

    # Errors
    "BLE001",
    "EM102", # Use error msg string not variable

    # -- Optional --
    "N803", # Lower case parameter name
    "EM101",
    "TRY003",
    "PLR2004", # Use variable as parameter not constant
    "D106", # Docstring is missing
]

[format]
docstring-code-format = true