target-version = "py310"

[lint]
select = ["ALL"]
ignore = [
    "D100",
    "D105", # Function doc for every function
    "S101",
    "INP001", # __init__ for implicit namespace
    "T201", # No print,
    
    # About TODO
    "TD002",
    "TD003",
    "FIX002",
]


[format]
exclude = [
    "**/test/**",
    "*.ipynb",
]